{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "prism-alert.fullname" . }}
  labels:
    {{- include "prism-alert.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "prism-alert.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ include "prism-alert.publicPort" . }}
      from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.ingress.podSelector | nindent 12 }}
{{- end }}
